### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by beesuns** [sharljimhtsin/madou_club_dumper#1]
OS 
```
OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22631 暂缺 Build 22631
OS 制造商:        Microsoft Corporation
```
PHP INFO 
```
PHP 8.3.7 (cli) (built: May  8 2024 08:56:56) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.3.7, Copyright (c) Zend Technologies
```
EXAMPLE CODE
```
php .\dump.php https://madou.club/%e8%8a%b1%e7%b5%ae-%e9%87%8e%e8%8a%b1%e5%9b%ad.html
```
ERROR MESSAGE
```
Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\babys\Downloads\madou_club_dumper-master\curl.php:16
Stack trace:
#0 C:\Users\babys\Downloads\madou_club_dumper-master\dump.php(13): curl('https://madou.c...')
#1 {main}
  thrown in C:\Users\babys\Downloads\madou_club_dumper-master\curl.php on line 16
```

**Comment by sharljimhtsin** [comment]
> OS 
> ```
> OS 名称:          Microsoft Windows 11 家庭中文版
> OS 版本:          10.0.22631 暂缺 Build 22631
> OS 制造商:        Microsoft Corporation
> ```
> PHP INFO 
> ```
> PHP 8.3.7 (cli) (built: May  8 2024 08:56:56) (ZTS Visual C++ 2019 x64)
> Copyright (c) The PHP Group
> Zend Engine v4.3.7, Copyright (c) Zend Technologies
> ```
> EXAMPLE CODE
> ```
> php .\dump.php https://madou.club/%e8%8a%b1%e7%b5%ae-%e9%87%8e%e8%8a%b1%e5%9b%ad.html
> ```
> ERROR MESSAGE
> ```
> Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\babys\Downloads\madou_club_dumper-master\curl.php:16
> Stack trace:
> #0 C:\Users\babys\Downloads\madou_club_dumper-master\dump.php(13): curl('https://madou.c...')
> #1 {main}
>   thrown in C:\Users\babys\Downloads\madou_club_dumper-master\curl.php on line 16
> ```

php curl 扩展没装吧
